### ISSUE TITLE
sfho_mass

### ISSUE THREAD

**Issue by dradice** [evanoconnor/NuLib#19]
I am trying to compile NuLib for the first time with electron capture on heavy nuclei turned on.

I enabled NUCLEI_HEMPEL in the make.inc. I downloaded the "sfho_frdm_spp.zip" archive from Hempel's page and I unpacked it into "./src/extra_code_and_tables/". Now my my compilation fails with:

weakrates/rateapprox.F90:66:44:
     use sfho_frdm_composition_module, only : sfho_mass

Indeed, I do not see sfho_mass defined anywhere in the SFHo code. Any idea of what I might be doing wrong?

Thanks,

David

PS.  I am using gfortran-6.3 from MacPorts on macOS.

**Comment by evanoconnor** [comment]
Hi David,

https://github.com/evanoconnor/NuLib/blob/master/README#L325-L336

Evan

**Comment by dradice** [comment]
Hi Evan,

thank you and sorry, I should have seen that!

David
