### ISSUE TITLE
stellarcollapse.org is down

### ISSUE THREAD

**Issue by suniverse** [evanoconnor/NuLib#39]
Stellarcollapse.org is down. Is there anywhere else that I can retrieve the eos data? Thank you.

**Comment by evanoconnor** [comment]
For now, I have all (most?) the files and can get them to you if you know which specific ones you want. ask here or send me an email evan.oconnor@astro.su.se

**Comment by suniverse** [comment]
I am wondering if there is a SFHo table that extends to lower density ~100g/cc that I can find somewhere . Or probably the source code to generate the SFHo table.

**Comment by evanoconnor** [comment]
Here is one that goes lower density.  Note, the compositions of this material is very wrong.  It is just taken from a higher density, and even there it assumes NSE, which is very likely wrong for such densities, so treat with caution especially if you are focusing on dynamics at these low densities.

http://ttt.astro.su.se/~eoco/Hempel_SFHoEOS_rho322_temp220_ye60_version_1.3_20190524.h5
